#!/usr/bin/env python3
"""Build a deterministic, generic Coppice KOReader plugin archive."""
from __future__ import annotations

import argparse
import io
import os
from pathlib import Path
import zipfile

ROOT = Path(__file__).resolve().parent
PLUGIN = ROOT / "coppice.koplugin"
OUTPUT = ROOT / "dist" / "coppice.koplugin.zip"
EPOCH = (1980, 1, 1, 0, 0, 0)


def lua_string(value: str) -> str:
    # Lua long-bracket strings avoid interpreting URLs or paths as escapes.
    if "]]" not in value:
        return "[[" + value + "]]"
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def config_source(values: dict[str, str]) -> bytes:
    lines = ["-- Generated by build.py. Non-secret defaults only.", "return {"]
    for key in ("server", "download_dir", "device_name"):
        value = values.get(key)
        if value:
            lines.append(f"    {key} = {lua_string(value)},")
    lines.append("}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def entries(config: dict[str, str]) -> list[tuple[str, bytes]]:
    if not PLUGIN.is_dir():
        raise SystemExit(f"missing plugin directory: {PLUGIN}")
    files: list[tuple[str, bytes]] = []
    for path in sorted(PLUGIN.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(PLUGIN).as_posix()
        if "stump" in rel.lower() or rel == "coppice_config.lua":
            raise SystemExit(f"unexpected legacy/config file in generic source: {rel}")
        files.append((f"coppice.koplugin/{rel}", path.read_bytes()))
    if config:
        files.append(("coppice.koplugin/coppice_config.lua", config_source(config)))
    return sorted(files)


def build(config: dict[str, str]) -> bytes:
    payload = io.BytesIO()
    with zipfile.ZipFile(payload, "w", compression=zipfile.ZIP_DEFLATED,
                         compresslevel=9) as archive:
        for name, data in entries(config):
            info = zipfile.ZipInfo(name, date_time=EPOCH)
            info.create_system = 3
            info.create_version = 20
            info.extract_version = 20
            info.flag_bits = 0
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            info.internal_attr = 0
            archive.writestr(info, data, compress_type=zipfile.ZIP_DEFLATED,
                             compresslevel=9)
    return payload.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--server-origin", help="non-secret server origin default")
    parser.add_argument("--download-dir", help="non-secret download directory default")
    parser.add_argument("--device-name", help="non-secret device display name default")
    args = parser.parse_args()
    config = {key: value for key, value in {
        "server": args.server_origin,
        "download_dir": args.download_dir,
        "device_name": args.device_name,
    }.items() if value}
    if "server" in config and not config["server"].startswith(("http://", "https://")):
        raise SystemExit("--server-origin must start with http:// or https://")
    data = build(config)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(data)
    print(f"{OUTPUT} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
